### ISSUE TITLE
Refactoring Epic

### ISSUE THREAD

**Issue by hudson-newey** [ecoacoustics/web-components#71]
#### Verification Grid

- [ ] The selection highlight box should use an intersection observer

#### CI

- [ ] Our CI is building components twice (once for publishing to the CDN and once for docs). We should consolidate this so that we only build the components once

#### Axes Component

- [ ] The axes component shouldn't attempt to re-render axes that would result in the same values
- [ ] The canvas that we use to calculate the font size in the axes component shouldn't

#### Data source

- [ ] We currently copy the entire files value when attempting to determine the files type. We should use a heap pointer instead (maybe through a mono-tuple)

#### Spectrogram

- [ ] We are currently double copying the entire audio file when using a mel scale
- [ ] We are currently burning cycles when waiting for the processor buffer to be ready. There should be a more efficient way to do this (e.g. through an event queue)

### Tests

- [ ] Finish `verification-grid-tile.spec.ts`
- [ ] Add sub-selection tests for `verification-grid.e2e.spec.ts`
- [ ] Add `media-controls.spec.ts` tests that assert users can change spectrogram options
- [ ] Add tests for `data-source.spec.ts` to assert that it can correctly detect file types
- [ ] Narrow TypeScript typing for test helper functions such as `getBrowserValue` so that it knows the type of the value associated with the `key` parameter
